# Site settings
author: Jessica Newell
title: The Perpetual Student
header-img: img/home-bg.png
email: j.lynnewell@gmail.com
copyright_name: Jessica Newell
description: > # this means to ignore newlines until "baseurl:"
  Just another step on this journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jessicalnewell

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
